import { useState } from "react";
import { ArrowRight, Check, Play, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { BrandMark, Modal, go } from "./_shared/ArckFitShared";
import "./_group.css";

export function Landing() {
  const [demo, setDemo] = useState(false);
  return <div className="arckfit-root min-h-[100dvh] bg-[#20334a] text-white">
    <nav className="mx-auto flex max-w-[1240px] items-center justify-between px-5 py-5 sm:px-8"><BrandMark light/><div className="hidden items-center gap-8 text-sm text-[#b9cbca] md:flex"><a href="#method" className="hover:text-white">The method</a><a href="#owners" className="hover:text-white">For owners</a><a href="#proof" className="hover:text-white">Proof</a></div><button onClick={() => go("MemberDashboard")} className="rounded-full border border-white/20 px-4 py-2 text-xs font-bold hover:border-[#d7f35c] hover:text-[#d7f35c]">Sign in</button></nav>
    <section className="arckfit-noise relative mx-auto grid max-w-[1240px] gap-12 overflow-hidden px-5 pb-20 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pb-32">
      <div className="relative z-10"><div className="mb-7 flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-[#d7f35c]"><span className="h-2 w-2 rounded-full bg-[#d7f35c] arckfit-pulse"/> Smart fitness management</div><h1 className="arckfit-display max-w-3xl text-5xl font-bold leading-[.98] tracking-[-.06em] sm:text-7xl">Train smarter.<br/><span className="text-[#d7f35c]">Live stronger.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-[#b9cbca] sm:text-lg">ArckFit turns every workout, member moment, and business decision into momentum you can measure.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => go("MemberDashboard")} className="flex items-center gap-2 rounded-full bg-[#d7f35c] px-5 py-3.5 text-sm font-bold text-[#20334a] hover:bg-[#e4fb76]">Explore the demo <ArrowRight size={16}/></button><button onClick={() => setDemo(true)} className="flex items-center gap-2 rounded-full border border-white/20 px-5 py-3.5 text-sm font-bold hover:border-white"><Play size={15} fill="currentColor"/> Watch the 90-sec tour</button></div><div className="mt-12 flex gap-8 border-t border-white/10 pt-5"><div><p className="arckfit-display text-2xl font-bold">4.8<span className="text-[#d7f35c]">/5</span></p><p className="mt-1 text-[11px] text-[#93aaa9]">member satisfaction</p></div><div><p className="arckfit-display text-2xl font-bold">31<span className="text-[#d7f35c]">%</span></p><p className="mt-1 text-[11px] text-[#93aaa9]">more weekly consistency</p></div></div></div>
      <div className="relative min-h-[410px]"><div className="absolute right-0 top-0 h-[330px] w-[330px] rounded-full bg-[#0f6268] opacity-80 blur-[1px] sm:h-[430px] sm:w-[430px]"/><div className="absolute right-5 top-8 w-[90%] max-w-[400px] rotate-[5deg] rounded-[28px] border border-white/15 bg-[#f5f7f4] p-4 text-[#20334a] shadow-2xl sm:right-12"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#0f6268]">Today / 07:30</p><p className="arckfit-display mt-1 text-xl font-bold">Push day</p></div><span className="rounded-full bg-[#d7f35c] px-3 py-1 text-[10px] font-bold">68% done</span></div><div className="mt-5 rounded-2xl bg-[#20334a] p-4 text-white"><div className="flex items-end justify-between"><div><p className="text-xs text-[#b9cbca]">Weekly load</p><p className="arckfit-display mt-1 text-3xl font-bold">8,420 <span className="text-sm font-normal text-[#b9cbca]">kg</span></p></div><TrendingUp className="text-[#d7f35c]"/></div><svg className="mt-4 h-16 w-full" viewBox="0 0 340 64" preserveAspectRatio="none"><path d="M0 54 C40 48 46 40 75 45 S112 28 145 38 S180 20 210 30 S250 10 280 22 S320 9 340 12" fill="none" stroke="#d7f35c" strokeWidth="3"/><path d="M0 54 C40 48 46 40 75 45 S112 28 145 38 S180 20 210 30 S250 10 280 22 S320 9 340 12 V64 H0Z" fill="#d7f35c" opacity=".1"/></svg></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#e1f0ed] p-3"><p className="text-[10px] text-[#70808c]">Consistency</p><p className="mt-1 text-lg font-bold">12 days</p></div><div className="rounded-2xl bg-[#fff0e7] p-3"><p className="text-[10px] text-[#70808c]">Next session</p><p className="mt-1 text-lg font-bold">Fri, 6:30</p></div></div></div><div className="absolute bottom-4 left-0 rounded-2xl border border-[#d7f35c]/30 bg-[#0f6268] px-4 py-3 text-sm shadow-xl sm:left-1"><ShieldCheck size={16} className="mr-2 inline text-[#d7f35c]"/>Built for human momentum</div></div>
    </section>
    <section id="method" className="bg-[#f5f7f4] px-5 py-20 text-[#20334a] sm:px-8 sm:py-28"><div className="mx-auto max-w-[1240px]"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#0f6268]">One rhythm, two sides</p><h2 className="arckfit-display mt-3 max-w-xl text-4xl font-bold leading-tight tracking-[-.05em] sm:text-5xl">A better gym is a connected gym.</h2><div className="mt-12 grid gap-5 md:grid-cols-3"><div className="arckfit-card arckfit-hover bg-[#d7f35c] p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#20334a] text-[#d7f35c]"><Sparkles size={18}/></span><h3 className="arckfit-display mt-8 text-2xl font-bold">For members</h3><p className="mt-3 text-sm leading-6 text-[#42555b]">A clear plan for today, a coach in your pocket, and progress that feels earned.</p></div><div className="arckfit-card arckfit-hover bg-[#e1f0ed] p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#0f6268] text-[#d7f35c]"><TrendingUp size={18}/></span><h3 className="arckfit-display mt-8 text-2xl font-bold">For trainers</h3><p className="mt-3 text-sm leading-6 text-[#42555b]">Turn check-ins into coaching signals and spend your time where it matters.</p></div><div id="owners" className="arckfit-card arckfit-hover bg-[#fff0e7] p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f39a64] text-[#20334a]"><ShieldCheck size={18}/></span><h3 className="arckfit-display mt-8 text-2xl font-bold">For owners</h3><p className="mt-3 text-sm leading-6 text-[#42555b]">A live view of retention, attendance, and the tiny signals that shape revenue.</p></div></div></div></section>
    <footer className="flex flex-col justify-between gap-5 bg-[#d7f35c] px-5 py-8 text-[#20334a] sm:flex-row sm:px-10"><BrandMark/><p className="text-xs font-semibold">© 2024 ArckFit · Train smarter. Live stronger.</p></footer>
    {demo && <Modal title="A quick tour of ArckFit" onClose={() => setDemo(false)}><p className="mt-4 text-sm leading-6 text-[#70808c]">See how Alex checks in, trains with Rahul, and turns each session into a stronger week.</p><button onClick={() => go("MemberDashboard")} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#20334a] py-3 text-sm font-bold text-white">Start the interactive tour <ArrowRight size={16}/></button></Modal>}
  </div>;
}