import { useState } from "react";
import { ArrowRight, CalendarDays, Clock3, Flame, Play, Target, Trophy } from "lucide-react";
import { AreaChart, Area, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { AppShell, Metric, ProgressBar, SectionHeading, Pill, go } from "./_shared/ArckFitShared";
import "./_group.css";

const chart = [{d:"M",v:32},{d:"T",v:48},{d:"W",v:40},{d:"T",v:62},{d:"F",v:54},{d:"S",v:77},{d:"S",v:69}];
export function MemberDashboard() {
  const [active, setActive] = useState("This week");
  return <AppShell title="Good morning, Alex" eyebrow="Wednesday, 24 April 2024"><div className="arckfit-rise flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#0f6268]">Your training pulse</p><h2 className="arckfit-display mt-2 text-3xl font-bold tracking-[-.05em] sm:text-4xl">Make today count.</h2><p className="mt-2 text-sm text-[#70808c]">You are 72% of the way to your May goal.</p></div><button onClick={() => go("Workout")} className="flex items-center justify-center gap-2 rounded-xl bg-[#20334a] px-5 py-3 text-sm font-bold text-white hover:bg-[#0f6268]"><Play size={15} fill="currentColor"/> Start workout</button></div>
    <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Weekly consistency" value="4 / 5" detail="+1 session vs last week" accent="lime"/><Metric label="Calories burned" value="1,840" detail="+12% from last week" accent="orange"/><Metric label="Current streak" value="12 days" detail="Personal best: 18 days" accent="teal"/><Metric label="Goal progress" value="72%" detail="8 days left in cycle" accent="lime"/></div>
    <div className="mt-8 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="arckfit-card arckfit-noise overflow-hidden bg-[#20334a] p-6 text-white sm:p-7"><div className="relative z-10 flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#d7f35c]">Today’s workout · 07:30</p><h3 className="arckfit-display mt-2 text-3xl font-bold tracking-[-.04em]">Push day</h3><p className="mt-2 text-sm text-[#b9cbca]">Chest, shoulders and triceps · 52 min</p></div><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold text-[#d7f35c]">4 exercises</span></div><div className="relative z-10 mt-8"><div className="flex items-center justify-between text-xs"><span className="text-[#b9cbca]">Ready when you are</span><span className="font-bold">0% complete</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-0 rounded-full bg-[#d7f35c]"/></div></div><div className="relative z-10 mt-8 flex flex-wrap gap-2">{["Incline press","Shoulder press","Cable fly","Tricep pushdown"].map(x => <Pill key={x}>{x}</Pill>)}</div></section><section className="arckfit-card p-6"><SectionHeading kicker="Upcoming" title="Trainer session"/><div className="flex items-center gap-4 rounded-2xl bg-[#e1f0ed] p-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#0f6268] text-[#d7f35c] text-sm font-bold">RS</div><div><p className="font-bold">Rahul Sharma</p><p className="mt-1 text-xs text-[#70808c]">Form & technique review</p></div></div><div className="mt-4 flex items-center justify-between border-t border-[#dfe7e3] pt-4 text-xs"><span className="flex items-center gap-2 text-[#70808c]"><CalendarDays size={14}/> Friday, 26 Apr</span><b>06:30 PM</b></div><button onClick={() => go("Trainers")} className="mt-4 flex items-center gap-2 text-xs font-bold text-[#0f6268]">View trainer <ArrowRight size={14}/></button></section></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="arckfit-card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><SectionHeading kicker="Momentum" title="Activity this week"/><div className="flex gap-1 rounded-xl bg-[#e9efea] p-1">{["This week","This month"].map(x=><button key={x} onClick={()=>setActive(x)} className={`rounded-lg px-3 py-2 text-[11px] font-bold ${active===x?"bg-[#fbfcfa] text-[#20334a] shadow-sm":"text-[#70808c]"}`}>{x}</button>)}</div></div><div className="mt-4 h-56"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="arckfitArea" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#0f6268" stopOpacity=".28"/><stop offset="100%" stopColor="#0f6268" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="d" axisLine={false} tickLine={false} tick={{fontSize:11,fill:"#91a0a0"}}/><Tooltip contentStyle={{borderRadius:12,border:"1px solid #dfe7e3",fontSize:12}}/><Area type="monotone" dataKey="v" stroke="#0f6268" strokeWidth={3} fill="url(#arckfitArea)"/></AreaChart></ResponsiveContainer></div></section><section className="arckfit-card p-6"><SectionHeading kicker="This cycle" title="Milestones"/>{[["5 workouts","Push the pace","bg-[#d7f35c]"],["72%","May goal","bg-[#f39a64]"],["12 days","Streak alive","bg-[#0f6268]"]].map(([n,l,c])=><div key={l} className="mb-3 flex items-center gap-3 rounded-2xl bg-[#f5f7f4] p-3"><span className={`grid h-10 w-10 place-items-center rounded-xl text-xs font-bold ${c} ${c==="bg-[#0f6268]"?"text-white":"text-[#20334a]"}`}>{n==="72%"?<Target size={16}/>:n==="12 days"?<Flame size={16}/>:<Trophy size={16}/>}</span><div><p className="text-sm font-bold">{n}</p><p className="text-[11px] text-[#70808c]">{l}</p></div></div>)}<div className="mt-4"><div className="mb-2 flex justify-between text-[11px] font-bold"><span>Goal progress</span><span>72%</span></div><ProgressBar value={72} color="bg-[#f39a64]"/></div></section></div>
  </AppShell>;
}