import { useEffect, useState } from "react";
import { ArrowLeft, Check, Clock3, Flame, Pause, Play, RotateCcw } from "lucide-react";
import { AppShell, Modal, ProgressBar, go } from "./_shared/ArckFitShared";
import "./_group.css";

const exercises = [["Incline barbell press","4 sets · 8 reps","52 kg"],["Seated shoulder press","3 sets · 10 reps","28 kg"],["Cable fly","3 sets · 12 reps","18 kg"],["Rope tricep pushdown","3 sets · 12 reps","24 kg"]];
export function Workout() {
  const [done, setDone] = useState<number[]>([0]); const [seconds, setSeconds] = useState(0); const [running, setRunning] = useState(false); const [finish, setFinish] = useState(false);
  useEffect(()=>{if(!running)return; const id=window.setInterval(()=>setSeconds(s=>s+1),1000); return()=>window.clearInterval(id)},[running]);
  const time = `${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
  return <AppShell title="Push day" eyebrow="Workout tracker"><div className="flex items-center justify-between"><button onClick={()=>go("MemberDashboard")} className="flex items-center gap-2 text-sm font-bold text-[#0f6268]"><ArrowLeft size={16}/> Back to dashboard</button><span className="rounded-full bg-[#d7f35c] px-3 py-1.5 text-[11px] font-bold">Wednesday, 24 Apr</span></div>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1fr_310px]"><div><div className="arckfit-card bg-[#20334a] p-6 text-white sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#d7f35c]">Push day · strength</p><h2 className="arckfit-display mt-2 text-4xl font-bold tracking-[-.05em]">Build the base.</h2><p className="mt-2 text-sm text-[#b9cbca]">Chest, shoulders and triceps · 4 movements</p></div><div className="text-right"><p className="arckfit-display text-3xl font-bold">{done.length * 25}%</p><p className="text-[10px] text-[#b9cbca]">complete</p></div></div><div className="mt-7 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#d7f35c] transition-all" style={{width:`${done.length*25}%`}}/></div></div><div className="mt-5 space-y-3">{exercises.map((e,i)=><div key={e[0]} className={`arckfit-card arckfit-hover flex items-center gap-4 p-4 ${done.includes(i)?"border-[#b9d33d] bg-[#eff7c9]":""}`}><button onClick={()=>setDone(d=>d.includes(i)?d.filter(x=>x!==i):[...d,i])} className={`grid h-10 w-10 shrink-0 place-items-center rounded-full border-2 transition ${done.includes(i)?"border-[#0f6268] bg-[#0f6268] text-[#d7f35c]":"border-[#dfe7e3] text-transparent hover:border-[#0f6268]"}`}><Check size={17}/></button><div className="min-w-0 flex-1"><p className={`font-bold ${done.includes(i)?"line-through opacity-60":""}`}>{e[0]}</p><p className="mt-1 text-xs text-[#70808c]">{e[1]}</p></div><span className="rounded-lg bg-[#e9efea] px-2.5 py-1.5 text-xs font-bold">{e[2]}</span></div>)}</div><button onClick={()=>setFinish(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#0f6268] py-4 text-sm font-bold text-white hover:bg-[#20334a]"><Check size={16}/> Finish workout</button></div>
      <aside className="space-y-4"><div className="arckfit-card p-6 text-center"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#0f6268]">Session timer</p><p className="arckfit-display mt-4 text-5xl font-bold tracking-[-.06em]">{time}</p><div className="mt-5 flex justify-center gap-2"><button onClick={()=>setRunning(!running)} className="grid h-11 w-11 place-items-center rounded-xl bg-[#20334a] text-white">{running?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}</button><button onClick={()=>{setSeconds(0);setRunning(false)}} className="grid h-11 w-11 place-items-center rounded-xl bg-[#e9efea]"><RotateCcw size={16}/></button></div></div><div className="arckfit-card p-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#0f6268]">Live stats</p><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#fff0e7] p-3"><Flame size={16} className="text-[#f39a64]"/><p className="mt-3 text-xl font-bold">{240 + done.length*72}</p><p className="text-[10px] text-[#70808c]">kcal est.</p></div><div className="rounded-xl bg-[#e1f0ed] p-3"><Clock3 size={16} className="text-[#0f6268]"/><p className="mt-3 text-xl font-bold">{Math.max(8, Math.round(seconds/60)+8)}</p><p className="text-[10px] text-[#70808c]">min active</p></div></div></div></aside></div>
    {finish && <Modal title="Strong work, Alex." onClose={()=>setFinish(false)}><div className="mt-5 rounded-2xl bg-[#d7f35c] p-4"><p className="text-sm font-bold">Push day is in the books.</p><p className="mt-1 text-xs text-[#42555b]">{done.length} of 4 movements completed · {240 + done.length*72} kcal estimated.</p></div><button onClick={()=>go("Progress")} className="mt-5 w-full rounded-xl bg-[#20334a] py-3 text-sm font-bold text-white">See your progress</button></Modal>}
  </AppShell>;
}