// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/repfi/AIAssistant.tsx": () => import("../components/mockups/repfi/AIAssistant.tsx"),
  "./components/mockups/repfi/AdminMembers.tsx": () => import("../components/mockups/repfi/AdminMembers.tsx"),
  "./components/mockups/repfi/Analytics.tsx": () => import("../components/mockups/repfi/Analytics.tsx"),
  "./components/mockups/repfi/Landing.tsx": () => import("../components/mockups/repfi/Landing.tsx"),
  "./components/mockups/repfi/MemberDashboard.tsx": () => import("../components/mockups/repfi/MemberDashboard.tsx"),
  "./components/mockups/repfi/Membership.tsx": () => import("../components/mockups/repfi/Membership.tsx"),
  "./components/mockups/repfi/Nutrition.tsx": () => import("../components/mockups/repfi/Nutrition.tsx"),
  "./components/mockups/repfi/OwnerDashboard.tsx": () => import("../components/mockups/repfi/OwnerDashboard.tsx"),
  "./components/mockups/repfi/Progress.tsx": () => import("../components/mockups/repfi/Progress.tsx"),
  "./components/mockups/repfi/Trainers.tsx": () => import("../components/mockups/repfi/Trainers.tsx"),
  "./components/mockups/repfi/Workout.tsx": () => import("../components/mockups/repfi/Workout.tsx")
};
