// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/arckfit/AIAssistant.tsx": () => import("../components/mockups/arckfit/AIAssistant.tsx"),
  "./components/mockups/arckfit/AdminMembers.tsx": () => import("../components/mockups/arckfit/AdminMembers.tsx"),
  "./components/mockups/arckfit/Analytics.tsx": () => import("../components/mockups/arckfit/Analytics.tsx"),
  "./components/mockups/arckfit/Landing.tsx": () => import("../components/mockups/arckfit/Landing.tsx"),
  "./components/mockups/arckfit/MemberDashboard.tsx": () => import("../components/mockups/arckfit/MemberDashboard.tsx"),
  "./components/mockups/arckfit/Membership.tsx": () => import("../components/mockups/arckfit/Membership.tsx"),
  "./components/mockups/arckfit/Nutrition.tsx": () => import("../components/mockups/arckfit/Nutrition.tsx"),
  "./components/mockups/arckfit/OwnerDashboard.tsx": () => import("../components/mockups/arckfit/OwnerDashboard.tsx"),
  "./components/mockups/arckfit/Progress.tsx": () => import("../components/mockups/arckfit/Progress.tsx"),
  "./components/mockups/arckfit/Trainers.tsx": () => import("../components/mockups/arckfit/Trainers.tsx"),
  "./components/mockups/arckfit/Workout.tsx": () => import("../components/mockups/arckfit/Workout.tsx")
};
